'use strict';
const BASE='9c273e86e6120c6a038160ccb0153b8b20425b84fc08a496281c1d1bcac492f6';
const chars={일:'079f',러:'03df',몬:'0493',코:'093a',딩:'0369',타:'0988',이:'079c',포:'0a27',몽:'0499',컬:'0923',링:'0445',픽:'0a68',셀:'05ef'};
const starters=[{id:152,old:'치코리타',name:'타이포몽',offset:0x1b1230,expected:'0901093a043e09885050',icon:'✳'},
{id:155,old:'브케인',name:'컬러링',offset:0x1b124e,expected:'054a0929079e50505050',icon:'⌘'},
{id:158,old:'리아코',name:'픽셀러',offset:0x1b126c,expected:'043e06c6093a50505050',icon:'T'}];
const $=id=>document.getElementById(id),hex=b=>Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');
let original=null,product=null,loadGeneration=0,editGeneration=0;
const sha=async b=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',b)));
function encode(name){if(!name.length||name.length>5||[...name].some(c=>!chars[c]))throw Error('이름은 등록된 글자로 1~5글자 입력하세요.');const h=[...name].map(c=>chars[c]).join('').padEnd(20,'50');return Uint8Array.from(h.match(/../g),x=>parseInt(x,16));}
function checksum(b){let h=0;for(let i=0x134;i<0x14d;i++)h=(h-b[i]-1)&255;const sum=b.reduce((s,x)=>s+x,0)-b[0x14e]-b[0x14f];return [h,sum&65535];}
function invalidate(){editGeneration++;product=null;['ips','output','manifest'].forEach(id=>$(id).disabled=true);$('result').textContent='';}
function names(){return starters.map(s=>$('name'+s.id).value.trim());}
function preview(){invalidate();$('build').disabled=!original;if(!original){$('diff').textContent='원본을 불러오면 변경 내용이 표시됩니다.';return;}try{const n=names();$('diff').replaceChildren(...starters.map((s,i)=>{const row=document.createElement('div');row.className='hex-row';const label=document.createElement('b');label.textContent='0x'+s.offset.toString(16).toUpperCase()+'  ';row.append(label,hex(original.slice(s.offset,s.offset+10))+' → '+hex(encode(n[i])));return row;}));}catch(e){$('diff').textContent=e.message;$('build').disabled=true;}}
for(const s of starters){const row=document.createElement('div');row.className='starter';row.innerHTML=`<div class="mon" aria-hidden="true">${s.icon}</div><div><strong>${s.old}</strong><small>NO. ${s.id} / ${s.offset.toString(16).toUpperCase()}</small></div><span class="arrow">→</span><label>새 이름<input type="text" id="name${s.id}" value="${s.name}" maxlength="5" aria-label="${s.old} 새 이름"></label>`;$('starters').append(row);$('name'+s.id).addEventListener('input',preview);}
$('reset').onclick=()=>{starters.forEach(s=>$('name'+s.id).value=s.name);preview();};
$('rom').onchange=async e=>{const generation=++loadGeneration;original=null;preview();const file=e.target.files[0];if(!file){$('status').textContent='아직 불러온 ROM이 없습니다.';return;}try{if(file.size!==2097152)throw Error('이 실험은 2 MB 한국어 골드 ROM만 지원합니다.');$('status').textContent='원본 해시 확인 중…';const b=new Uint8Array(await file.arrayBuffer());const digest=await sha(b);if(generation!==loadGeneration)return;if(digest!==BASE)throw Error('기준 ROM과 SHA-256이 다릅니다. 수정본 또는 다른 버전은 사용할 수 없습니다.');for(const s of starters)if(hex(b.slice(s.offset,s.offset+10))!==s.expected)throw Error('이름 테이블이 일치하지 않습니다.');const [h,sum]=checksum(b);if(h!==b[0x14d]||sum!==(b[0x14e]*256+b[0x14f]))throw Error('체크섬 검증 실패');original=b;$('status').textContent='✓ 한국어 골드 확인 완료 · 체크섬 정상';preview();}catch(err){if(generation===loadGeneration){$('status').textContent=err.message;original=null;preview();}}};
function ips(before,after){const parts=[80,65,84,67,72];for(let i=0;i<before.length;){if(before[i]===after[i]){i++;continue;}const start=i;while(i<before.length&&before[i]!==after[i]&&i-start<65535)i++;const n=i-start;parts.push(start>>16,(start>>8)&255,start&255,n>>8,n&255,...after.slice(start,i));}parts.push(69,79,70);return new Uint8Array(parts);}
$('build').onclick=async()=>{if(!original)return;const generation=editGeneration,source=original;try{const selected=names(),out=source.slice(),records=[];starters.forEach((s,i)=>{const data=encode(selected[i]);out.set(data,s.offset);records.push({species_id:s.id,offset:s.offset,old_name:s.old,new_name:selected[i],before_hex:s.expected,after_hex:hex(data)});});out[0x14d]=checksum(out)[0];const sum=checksum(out)[1];out[0x14e]=sum>>8;out[0x14f]=sum&255;const hash=await sha(out);if(generation!==editGeneration||source!==original)return;const changed=out.reduce((n,x,i)=>n+(x!==source[i]),0);product={rom:out,ips:ips(source,out),manifest:{format:'designmon-gold-patch-v1',source_sha256:BASE,output_sha256:hash,scope:'Species display names only; graphics, dialogue and game rules are unchanged.',records,changed_bytes:changed}};$('result').textContent=`✓ 검증 완료 · ${changed}바이트 변경 · 체크섬 갱신 완료. 아래에서 결과를 내려받으세요.`;['ips','output','manifest'].forEach(id=>$(id).disabled=false);}catch(e){invalidate();$('result').textContent=e.message;}};
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('ips').onclick=()=>product&&download(product.ips,'designmon-starters.ips','application/octet-stream');
$('output').onclick=()=>product&&download(product.rom,'designmon-starters.gbc','application/octet-stream');
$('manifest').onclick=()=>product&&download(JSON.stringify(product.manifest,null,2),'manifest.json','application/json');
