const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const [original,expectedRom,expectedIps,output]=process.argv.slice(2);
if(!output)throw Error('Usage: node tests/browser.cjs ORIGINAL_ROM EXPECTED_ROM EXPECTED_IPS OUTPUT_DIR');
fs.mkdirSync(output,{recursive:true});
(async()=>{
const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(pathToFileURL(path.resolve(__dirname,'../tools/rom-lab/index.html')).href);
await page.locator('#rom').setInputFiles(original);
await page.locator('#build').waitFor();
await page.waitForFunction(()=>!document.getElementById('build').disabled);
await page.locator('#build').click();
await page.waitForFunction(()=>!document.getElementById('output').disabled);
const expected=fs.readFileSync(expectedRom);
const downloadPromise=page.waitForEvent('download');await page.locator('#output').click();const d=await downloadPromise;
const tmp=path.join(output,'browser-output.gbc');await d.saveAs(tmp);
if(!fs.readFileSync(tmp).equals(expected))throw Error('Browser/Python ROM mismatch');
const ipsPromise=page.waitForEvent('download');await page.locator('#ips').click();await (await ipsPromise).saveAs(path.join(output,'browser-output.ips'));
if(!fs.readFileSync(path.join(output,'browser-output.ips')).equals(fs.readFileSync(expectedIps)))throw Error('IPS mismatch');
await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
await page.locator('#name152').fill('잘못된글자');
if(!await page.locator('#build').isDisabled()||!await page.locator('#output').isDisabled())throw Error('Invalid edit not gated');
await page.locator('#reset').click();await page.locator('#build').click();await page.waitForFunction(()=>!document.getElementById('output').disabled);
await page.locator('#rom').setInputFiles(tmp);await page.waitForFunction(()=>document.getElementById('status').textContent.includes('다릅니다'));
if(!await page.locator('#build').isDisabled()||!await page.locator('#output').isDisabled())throw Error('Wrong hash not gated');
await page.setViewportSize({width:390,height:844});
await page.locator('#rom').setInputFiles(original);await page.waitForFunction(()=>!document.getElementById('build').disabled);
await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
console.log(JSON.stringify({browser:'Chrome / Playwright',rom_parity:true,ips_parity:true,invalid_name_rejected:true,modified_rom_rejected:true,mobile_no_overflow:true,page_errors:errors}));
if(errors.length)throw Error('Page errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
