const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
let debugPage;
const C=require('../web/core'),D=require('../web/data');
const output=process.env.DESIGNMON_TEST_OUTPUT||'/tmp/designmon-web-verification';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=pathToFileURL(path.resolve(__dirname,'../web/index.html')).href;await page.goto(url);await page.screenshot({path:path.join(output,'title.png')});await page.click('[data-action=new]');for(let i=0;i<3;i++)await page.click('[data-action=advance]');await page.click('[data-action=starter][data-id=typo]');for(let i=0;i<3;i++)await page.click('[data-action=advance]');
debugPage=page;
const state=()=>page.evaluate(()=>Designmon.getState());
async function walk(tx,ty){let s=await state(),m=D.maps[s.map],q=[[s.x,s.y,[]]],seen=new Set([s.x+','+s.y]),route;for(let i=0;i<q.length;i++){let[x,y,p]=q[i];if(x===tx&&y===ty){route=p;break;}for(const[dir,dx,dy]of[['ArrowUp',0,-1],['ArrowDown',0,1],['ArrowLeft',-1,0],['ArrowRight',1,0]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(seen.has(k)||C.blocked(m,nx,ny))continue;if(m.portals.some(p=>p.x===nx&&p.y===ny)&&!(nx===tx&&ny===ty))continue;seen.add(k);q.push([nx,ny,p.concat(dir)]);}}assert.ok(route,`route ${s.map} ${tx},${ty}`);for(const key of route){const before=await state();await page.keyboard.down(key);await page.waitForFunction(({x,y,map})=>{const s=Designmon.getState();return s.x!==x||s.y!==y||s.map!==map;},before,{timeout:2000});await page.keyboard.up(key);}}
async function talk(x,y){await walk(x,y+1);await page.keyboard.down('ArrowUp');await page.waitForFunction(()=>Designmon.getState().dir==='up');await page.keyboard.up('ArrowUp');await page.keyboard.press('Enter');}
await walk(10,13);assert.equal((await state()).map,'town');await walk(24,20);assert.equal((await state()).map,'guild');
for(const [i,p]of D.projects.entries()){console.log('Project',p.id);await talk([5,10,15][i],5);await page.click('[data-action=begin]');if(!i)await page.screenshot({path:path.join(output,'battle.png')});while(!(await state()).battle.result){const s=await state(),b=s.battle;let selector=b.turn===1?'[data-type=scope]':b.agreement<p.goal?'[data-type=explain]':s.condition[b.active]<30&&s.items.coffee?'item':'[data-type=submit]';if(selector==='item'){await page.click('[data-action=items]');await page.click('[data-action=item][data-id=coffee]');}else await page.click(selector);await page.waitForTimeout(240);}assert.equal((await state()).battle.result,'won',p.id);await page.click('[data-action=finish]');while(await page.evaluate(()=>Designmon.getMode()==='dialog'))await page.click('[data-action=advance]');if(i<2){await walk(10,13);await talk(23,11);await page.click('[data-action=advance]');await page.click('[data-action=advance]');await walk(24,20);}}
assert.equal((await state()).owned.length,8);await page.click('[data-action=journal]');await page.screenshot({path:path.join(output,'completed.png')});await page.click('[data-action=close]');await page.reload();await page.click('[data-action=continue]');assert.equal((await state()).completed.length,3);
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});debugPage=mobile;console.log('Mobile');mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);await mobile.click('[data-action=new]');for(let i=0;i<3;i++)await mobile.click('[data-action=advance]');await mobile.click('[data-action=starter][data-id=pixel]');for(let i=0;i<3;i++)await mobile.click('[data-action=advance]');const before=await mobile.evaluate(()=>Designmon.getState().y);const down=mobile.locator('[data-dir=down]');await down.dispatchEvent('pointerdown',{pointerId:1});await mobile.waitForTimeout(300);await down.dispatchEvent('pointerup',{pointerId:1});assert.ok(await mobile.evaluate(()=>Designmon.getState().y)>before);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: keyboard exploration, three projects, eight companions, ending, reload, mobile layout and touch movement; no browser errors.');await browser.close();})().catch(async e=>{console.error(e.message);if(debugPage){await debugPage.screenshot({path:output+'/failure.png',fullPage:true});console.log(await debugPage.evaluate(()=>({mode:Designmon.getMode(),state:Designmon.getState(),buttons:[...document.querySelectorAll('[data-action=advance]')].map(e=>e.getBoundingClientRect().toJSON())})));}process.exit(1);});
