(function(){'use strict';
const $=id=>document.getElementById(id),ctx=$('screen').getContext('2d'),frame=ctx.createImageData(160,144),HZ=4194304,AUDIO=2048;
let M,e=0,romPtr=0,joy=0,digest='',paused=true,last=0,frames=0,audio=null,sound=false,audioTime=0,loading=false;
const message=t=>$('status').textContent=t,bytes=(ptr,n)=>new Uint8Array(M.HEAPU8.buffer,ptr,n);
const ready=Binjgb({wasmBinary:Uint8Array.from(atob(window.BINJGB_WASM),c=>c.charCodeAt(0)),print:()=>{},printErr:()=>{}}).then(m=>M=m);
function key(k,down){if(e)M['_set_joyp_'+k](e,down?1:0);}
function release(){for(const k of ['up','down','left','right','A','B','start','select'])key(k,false);document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
function draw(){if(!e)return;frame.data.set(bytes(M._get_frame_buffer_ptr(e),M._get_frame_buffer_size(e)));ctx.putImageData(frame,0,0);}
function packet(write,data){const p=M._state_file_data_new(e);try{const b=bytes(M._get_file_data_ptr(p),M._get_file_data_size(p));if(write){if(M._emulator_write_state(e,p)!==0)throw Error('상태 저장 실패');return Uint8Array.from(b);}if(data.length!==b.length)throw Error('상태 파일 크기가 맞지 않습니다.');b.set(data);if(M._emulator_read_state(e,p)!==0)throw Error('상태 파일을 읽을 수 없습니다.');}finally{M._file_data_delete(p);}}
function b64(b){let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s);}
function snapshot(){return {format:'designmon-binjgb-v1',rom:digest,state:b64(packet(true)),frame:b64(new Uint8Array(frame.data))};}
function restore(v){if(!v||v.format!=='designmon-binjgb-v1'||v.rom!==digest||typeof v.state!=='string')throw Error('현재 ROM과 일치하는 상태 파일이 아닙니다.');const data=Uint8Array.from(atob(v.state),c=>c.charCodeAt(0)),pixels=v.frame?Uint8Array.from(atob(v.frame),c=>c.charCodeAt(0)):null;if(pixels&&pixels.length!==frame.data.length)throw Error('화면 상태 크기가 맞지 않습니다.');const backup=packet(true);try{packet(false,data);}catch(err){packet(false,backup);throw err;}release();last=0;audioTime=0;if(pixels){frame.data.set(pixels);ctx.putImageData(frame,0,0);}else draw();}
function storageKey(){return 'designmon-rom-state-'+digest;}
function audioPush(){if(!sound||!audio||audio.state!=='running')return;const raw=bytes(M._get_audio_buffer_ptr(e),M._get_audio_buffer_capacity(e)),buf=audio.createBuffer(2,AUDIO,audio.sampleRate);for(let c=0;c<2;c++){const out=buf.getChannelData(c);for(let i=0;i<AUDIO;i++)out[i]=raw[i*2+c]/255*.35;}const src=audio.createBufferSource();src.buffer=buf;src.connect(audio.destination);audioTime=Math.max(audioTime,audio.currentTime+.04);if(audioTime>audio.currentTime+.3)audioTime=audio.currentTime+.04;src.start(audioTime);audioTime+=AUDIO/audio.sampleRate;}
function tick(t){if(e&&!paused&&!document.hidden){const dt=Math.min(.05,Math.max(0,(t-(last||t))/1000)),until=M._emulator_get_ticks_f64(e)+dt*HZ;while(true){const event=M._emulator_run_until_f64(e,until);if(event&1){draw();frames++;}if(event&2)audioPush();if(event&4)break;}}last=t;requestAnimationFrame(tick);}
$('romFile').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file||loading)return;loading=true;paused=true;release();try{if(file.size<32768||file.size>8388608||file.size%16384)throw Error('지원하는 GB/GBC ROM 크기가 아닙니다.');const data=new Uint8Array(await file.arrayBuffer());let sum=0;for(let i=0x134;i<=0x14c;i++)sum=(sum-data[i]-1)&255;if(sum!==data[0x14d])throw Error('ROM 헤더 체크섬이 일치하지 않습니다.');await ready;const hash=await crypto.subtle.digest('SHA-256',data);digest=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');if(e){M._emulator_delete(e);M._free(romPtr);M._joypad_delete(joy);e=0;}try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();}catch{}const size=(data.length+32767)&~32767;romPtr=M._malloc(size);bytes(romPtr,size).fill(0);bytes(romPtr,data.length).set(data);e=M._emulator_new_simple(romPtr,size,audio?.sampleRate||44100,AUDIO,2);if(!e){M._free(romPtr);throw Error('에뮬레이터가 이 ROM을 열지 못했습니다.');}joy=M._joypad_new();M._emulator_set_default_joypad_callback(e,joy);release();frames=0;last=0;paused=false;for(const id of ['pause','sound','save','load','export','stateFile'])$(id).disabled=false;$('pause').textContent='일시정지';message(file.name+' · 실행 중 · SHA-256 '+digest.slice(0,12));}catch(err){message(err.message);}finally{loading=false;}};
$('pause').onclick=()=>{paused=!paused;release();last=0;$('pause').textContent=paused?'계속 실행':'일시정지';if(paused)audio?.suspend();else if(sound)audio?.resume();};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='소리 '+(sound?'ON':'OFF');if(sound)audio?.resume();else audio?.suspend();audioTime=0;};
$('save').onclick=()=>{try{localStorage.setItem(storageKey(),JSON.stringify(snapshot()));message('현재 상태를 브라우저에 저장했습니다.');}catch(err){message('저장 실패: '+err.message+' · 파일 내보내기를 이용하세요.');}};
$('load').onclick=()=>{try{const raw=localStorage.getItem(storageKey());if(!raw)throw Error('이 ROM의 저장 상태가 없습니다.');restore(JSON.parse(raw));message('저장한 상태로 돌아왔습니다.');}catch(err){message('불러오기 실패: '+err.message);}};
$('export').onclick=()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot())],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='designmon-rom-'+digest.slice(0,12)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('상태 파일을 내보냈습니다.');}catch(err){message(err.message);}};
$('stateFile').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file)return;try{if(file.size>3000000)throw Error('파일이 너무 큽니다.');const v=JSON.parse(await file.text());restore(v);message('상태 파일을 불러왔습니다.');}catch(err){message('불러오기 실패: '+err.message);}};
const mapping={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',KeyX:'A',KeyZ:'B',Enter:'start',ShiftLeft:'select',ShiftRight:'select'};
for(const type of ['keydown','keyup'])window.addEventListener(type,ev=>{if(ev.ctrlKey||ev.metaKey||ev.altKey||ev.target.tagName==='INPUT')return;const k=mapping[ev.code];if(k&&e){ev.preventDefault();key(k,type==='keydown');}});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=ev=>{ev.preventDefault();b.setPointerCapture(ev.pointerId);key(b.dataset.key,true);b.classList.add('pressed');};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{key(b.dataset.key,false);b.classList.remove('pressed');});}
window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();last=0;if(document.hidden)audio?.suspend();else if(sound&&!paused)audio?.resume();});
window.DesignmonROM={status:()=>({loaded:!!e,paused,frames,ticks:e?M._emulator_get_ticks_f64(e):0,digest})};ready.catch(err=>message('실행 엔진 로드 실패: '+err.message));requestAnimationFrame(tick);
})();
