/* Optional editors; game remains full-screen until the user opens them. */
(function(root){'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);let source=null,restoringSource=false,sourceCacheError='',sourcePath='',sourceQuery='',species=152,mapId='',map=null;
function save(data,name,type='application/octet-stream'){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function guard(fn,message){return()=>{try{Promise.resolve(fn()).catch(e=>message(e.message));}catch(e){message(e.message);}};}
function numbers(value){const lines=value.trim().split(/\n/).filter(v=>v.trim());return lines.map(l=>l.trim().split(/[\s,]+/).map(Number));}
function renderEvolution(project,panel,o){const data=project.getEvolutionLearnset(species);panel.innerHTML='<select id="evoSpecies" aria-label="몬스터">'+Array.from({length:251},(_,i)=>'<option value="'+(i+1)+'" '+(i+1===species?'selected':'')+'>'+ (i+1)+' · '+esc(project.getPokemon(i+1).name)+'</option>').join('')+'</select><p class="note">진화: 방식, 조건, 대상 번호, 비교값(방식 5)<br>방식 1 레벨 · 2 아이템 · 3 교환 · 4 친밀도 · 5 능력치 비교</p><textarea id="evolutions" aria-label="진화 조건">'+data.evolutions.map(e=>[e.method,e.parameter,e.species,...(e.comparison===undefined?[]:[e.comparison])].join(', ')).join('\n')+'</textarea><p class="note">레벨업: 레벨, 기술 번호</p><textarea id="learnset" aria-label="레벨업 기술">'+data.learnset.map(e=>e.level+', '+e.move).join('\n')+'</textarea><button id="evoCommit" class="primary">적용</button>';$('evoSpecies').onchange=e=>{species=+e.target.value;renderEvolution(project,panel,o);};$('evoCommit').onclick=guard(()=>{const evolutions=numbers($('evolutions').value).map(([method,parameter,species,comparison])=>({method,parameter,species,...(comparison===undefined?{}:{comparison})})),learnset=numbers($('learnset').value).map(([level,move])=>({level,move}));project.setEvolutionLearnset(species,{evolutions,learnset});o.changed();},o.message);}
async function importSource(input,panel,o,remember=true){source=await DesignmonSourceProject.import(input);sourcePath='';if(remember)await cacheSource(o);sourceMessage(o,'소스 '+source.metadata.fileCount+'개를 열었습니다.');if(panel.querySelector('#sourceBody'))renderSource(panel,o);}
async function cacheSource(o){sourceCacheError='';if(source&&o.saveSource){try{await o.saveSource(source.export());}catch{sourceCacheError='자동 저장 실패. 소스를 내보내세요.';}}}
function sourceMessage(o,text){o.message(text+(sourceCacheError?' · '+sourceCacheError:''));}
async function restoreSource(panel,o){if(restoringSource)return;restoringSource=true;try{let saved=null;try{saved=await o.loadSource?.();}catch{}if(saved){try{await importSource(saved,panel,o,false);return;}catch(e){o.message(e.message);}}if(root.GOLD_EMBEDDED_SOURCE){const packed=Uint8Array.from(atob(root.GOLD_EMBEDDED_SOURCE),c=>c.charCodeAt(0));await importSource(new TextDecoder().decode(fflate.gunzipSync(packed)),panel,o,false);root.GOLD_EMBEDDED_SOURCE=null;}}finally{restoringSource=false;}}
function renderSource(panel,o){panel.innerHTML='<div class="row"><button id="sourceImport">소스 프로젝트 열기</button><button id="sourceExport" '+(!source?'disabled':'')+'>내보내기</button><button id="sourceBuild" class="primary" '+(!source?'disabled':'')+'>빌드 · 실행</button></div><input type="file" id="sourceFile" accept=".json" hidden><div id="sourceBody"></div>';$('sourceImport').onclick=()=>$('sourceFile').click();$('sourceFile').onchange=e=>{const f=e.target.files[0];if(f)guard(()=>importSource(f,panel,o),o.message)();};$('sourceExport').onclick=guard(()=>save(source.export(),'gold-source-project.json','application/json'),o.message);$('sourceBuild').onclick=guard(async()=>{if(!source)return;const button=$('sourceBuild');button.disabled=true;try{const result=await source.build({onProgress:p=>{o.message('빌드 '+p.completed+'/'+p.total+' · '+p.file);}});await cacheSource(o);const notice=await o.launchSource(result);sourceMessage(o,notice||(result.identicalToOriginal?'원본과 동일한 빌드 · 실행':'수정 소스 빌드 · 실행'));}finally{button.disabled=false;}},o.message);
 if(!source){$('sourceBody').innerHTML='<p class="note">골드 소스 프로젝트 JSON을 여세요.</p>';guard(()=>restoreSource(panel,o),o.message)();return;}
 const body=$('sourceBody');body.innerHTML='<div class="row"><input id="sourceSearch" placeholder="파일 검색" aria-label="소스 파일 검색" value="'+esc(sourceQuery)+'"><span id="sourceCount"></span></div><select id="sourcePaths" size="8" aria-label="소스 파일"></select><p id="sourceName" class="note"></p><textarea id="sourceText" spellcheck="false" aria-label="소스 편집"></textarea><div class="row"><button id="sourceCommit">파일 적용</button><button id="sourceDownload">파일 내려받기</button><button id="sourceReplace">파일 교체</button></div><input type="file" id="sourceReplacement" hidden>';
 function populate(){const files=source.list(sourceQuery);$('sourceCount').textContent=files.length+'개';$('sourcePaths').innerHTML=files.map(f=>'<option value="'+esc(f.path)+'" '+(f.path===sourcePath?'selected':'')+'>'+ (f.changed?'● ':'')+esc(f.path)+'</option>').join('');if(!sourcePath&&files.length)sourcePath=files[0].path;show();}
 function show(){if(!sourcePath||!source.project.files[sourcePath])return;const data=source.read(sourcePath),binary=typeof data!=='string';$('sourcePaths').value=sourcePath;$('sourceName').textContent=sourcePath+(binary?' · 16진수':'');$('sourceText').value=binary?GoldProject.hex(data).match(/.{1,64}/g)?.join('\n')||'':data;}
 $('sourceSearch').oninput=e=>{sourceQuery=e.target.value;populate();};$('sourcePaths').onchange=e=>{sourcePath=e.target.value;show();};$('sourceCommit').onclick=guard(async()=>{const value=$('sourceText').value;source.write(sourcePath,typeof source.read(sourcePath)==='string'?value:GoldProject.unhex(value.replace(/\s/g,'')));await cacheSource(o);sourceMessage(o,'파일 적용 · 빌드하면 게임에 반영됩니다.');populate();},o.message);$('sourceDownload').onclick=guard(()=>save(source.read(sourcePath),sourcePath.split('/').pop()),o.message);$('sourceReplace').onclick=()=>$('sourceReplacement').click();$('sourceReplacement').onchange=e=>{const f=e.target.files[0];if(f)guard(async()=>{if(f.size>16000000)throw Error('파일이 너무 큽니다.');source.write(sourcePath,typeof source.read(sourcePath)==='string'?await f.text():new Uint8Array(await f.arrayBuffer()));await cacheSource(o);show();sourceMessage(o,'파일을 교체했습니다.');},o.message)();};populate();}
root.GoldPanels={render(tab,project,panel,options){if(tab==='evolution'){renderEvolution(project,panel,options);return true;}if(tab==='source'){renderSource(panel,options);return true;}return false;},source:()=>source};
})(globalThis);
