/* Lossless, local-only Korean Gold ROM projects. Original bytecode, scripts,
 * maps, sound and graphics stay intact unless the user explicitly edits them. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./rom-schema.js'):root.GoldSchema);if(typeof module==='object'&&module.exports)module.exports=api;else root.GoldProject=api;})(typeof globalThis!=='undefined'?globalThis:this,function(S){'use strict';
const privateState=new WeakMap(), hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
function unhex(s){if(typeof s!=='string'||s.length%2||!/^[0-9a-f]*$/i.test(s))throw Error('올바른 16진수 바이트가 아닙니다.');return Uint8Array.from(s.match(/../g)||[],x=>parseInt(x,16));}
function bytes(input){if(input instanceof ArrayBuffer)return new Uint8Array(input.slice(0));if(ArrayBuffer.isView(input))return new Uint8Array(input.buffer.slice(input.byteOffset,input.byteOffset+input.byteLength));if(Array.isArray(input)&&input.every(x=>Number.isInteger(x)&&x>=0&&x<=255))return Uint8Array.from(input);throw Error('바이트 배열이 필요합니다.');}
function integer(n,min,max,label='값'){if(!Number.isInteger(n)||n<min||n>max)throw Error(label+' 범위: '+min+'–'+max);return n;}
function range(offset,length,size){integer(offset,0,size,'주소');integer(length,0,size-offset,'길이');}
async function hash(input){const b=bytes(input);if(typeof require==='function')return require('node:crypto').createHash('sha256').update(b).digest('hex');if(!globalThis.crypto?.subtle)throw Error('이 브라우저에서는 SHA-256 검증을 사용할 수 없습니다.');return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',b)));}
const encodeMap=new Map(),decodeMap=new Map();
for(const [token,value] of Object.entries(S.characters)){encodeMap.set(token,[value]);if(!decodeMap.has(value))decodeMap.set(value,token);}
// The regular text font uses Latin glyphs in these overlapping naming-screen slots.
for(const c of 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789')decodeMap.set(S.characters[c],c);
for(const [table,row] of Object.entries(S.koreanTables))Array.from(row).forEach((ch,index)=>{if(ch!=='\0'){const n=Number(table)*256+index;encodeMap.set(ch,[Number(table),index]);decodeMap.set(n,ch);}});
const tokens=[...encodeMap.keys()].sort((a,b)=>b.length-a.length);
function encodeText(text,{length=null,terminate=false}={}){if(typeof text!=='string')throw Error('문자열이 필요합니다.');const out=[];for(let i=0;i<text.length;){const literal=text.slice(i).match(/^\{([0-9a-f]{2}(?:[0-9a-f]{2})?)\}/i);if(literal){out.push(...unhex(literal[1]));i+=literal[0].length;continue;}const t=tokens.find(t=>text.startsWith(t,i));if(!t)throw Error('한글 골드 문자표에 없는 글자: '+String.fromCodePoint(text.codePointAt(i)));out.push(...encodeMap.get(t));i+=t.length;}if(terminate)out.push(0x50);if(length!==null){integer(length,0,65535,'문자 영역');if(out.length>length)throw Error('인코딩된 글자가 '+length+'바이트를 넘습니다 ('+out.length+'바이트).');while(out.length<length)out.push(0x50);}return Uint8Array.from(out);}
function decodeText(input,{stopAtTerminator=true}={}){const b=bytes(input);let out='';for(let i=0;i<b.length;i++){const first=b[i];if(first===0x50&&stopAtTerminator)break;let code=first,raw=[first];if(first>=1&&first<=11&&i+1<b.length){code=first*256+b[++i];raw.push(b[i]);}out+=decodeMap.get(code)??'{'+hex(raw).toUpperCase()+'}';}return out;}
function checksum(input){const b=bytes(input);let header=0;for(let i=0x134;i<=0x14c;i++)header=(header-b[i]-1)&255;let global=0;for(let i=0;i<b.length;i++)if(i!==0x14e&&i!==0x14f)global=(global+b[i])&65535;return{header,global,headerValid:header===b[0x14d],globalValid:global===((b[0x14e]<<8)|b[0x14f])};}
function fixChecksums(b){let n=0;for(let i=0x134;i<=0x14c;i++)n=(n-b[i]-1)&255;b[0x14d]=n;n=0;for(let i=0;i<b.length;i++)if(i!==0x14e&&i!==0x14f)n=(n+b[i])&65535;b[0x14e]=n>>>8;b[0x14f]=n&255;return b;}
function offset(bank,address){integer(bank,0,127,'ROM 뱅크');integer(address,bank?0x4000:0,bank?0x7fff:0x3fff,'CPU 주소');return bank*0x4000+(bank?address-0x4000:address);}
function diff(before,after){if(before.length!==after.length)throw Error('ROM 크기가 달라졌습니다.');const chunks=[];for(let i=0;i<before.length;){if(before[i]===after[i]){i++;continue;}const start=i;while(i<before.length&&before[i]!==after[i]&&i-start<65535)i++;chunks.push({offset:start,before:hex(before.slice(start,i)),after:hex(after.slice(start,i))});}return chunks;}
function makeIPS(before,after){const out=[80,65,84,67,72];for(const c of diff(before,after)){let p=c.offset,d=unhex(c.after);if(p===0x454f46){p--;d=Uint8Array.from([after[p],...d]);}for(let i=0;i<d.length;i+=65535){const n=Math.min(65535,d.length-i),a=p+i;out.push(a>>>16,(a>>>8)&255,a&255,n>>>8,n&255,...d.slice(i,i+n));}}out.push(69,79,70);return Uint8Array.from(out);}
function applyIPS(original,patch){const b=bytes(original),p=bytes(patch);if(hex(p.slice(0,5))!=='5041544348')throw Error('IPS 헤더가 올바르지 않습니다.');let at=5;while(at<p.length){if(at+3>p.length)throw Error('잘린 IPS 주소입니다.');const a=(p[at++]<<16)|(p[at++]<<8)|p[at++];if(a===0x454f46){if(at!==p.length)throw Error('ROM 크기 변경 IPS는 지원하지 않습니다.');return b;}if(at+2>p.length)throw Error('잘린 IPS 길이입니다.');const n=(p[at++]<<8)|p[at++];if(n){range(a,n,b.length);if(at+n>p.length)throw Error('잘린 IPS 데이터입니다.');b.set(p.slice(at,at+n),a);at+=n;}else{if(at+3>p.length)throw Error('잘린 IPS RLE입니다.');const count=(p[at++]<<8)|p[at++],v=p[at++];range(a,count,b.length);b.fill(v,a,a+count);}}throw Error('IPS 종료 마커가 없습니다.');}
function decompress(input,start=0,{maxOutput=65536}={}){const b=bytes(input),out=[];let p=start;const read=()=>{if(p>=b.length)throw Error('잘린 LZ 스트림입니다.');return b[p++];};while(p<b.length){let c=read();if(c===255)return{bytes:Uint8Array.from(out),consumed:p-start};let cmd=c>>>5,n=(c&31)+1;if(cmd===7){cmd=(c>>>2)&7;n=(((c&3)<<8)|read())+1;if(cmd>6)throw Error('지원하지 않는 LZ 명령입니다.');}if(out.length+n>maxOutput)throw Error('LZ 출력 한도를 넘었습니다.');if(cmd===0){for(let i=0;i<n;i++)out.push(read());}else if(cmd===1){const v=read();for(let i=0;i<n;i++)out.push(v);}else if(cmd===2){const a=read(),d=read();for(let i=0;i<n;i++)out.push(i%2?d:a);}else if(cmd===3){for(let i=0;i<n;i++)out.push(0);}else{const a=read();let from=a&128?out.length-(a&127)-1:(a<<8)|read();for(let i=0;i<n;i++){if(from<0||from>=out.length)throw Error('LZ 참조가 범위를 벗어났습니다.');let v=out[from];if(cmd===5){let reversed=0;for(let k=0;k<8;k++)reversed=(reversed<<1)|((v>>>k)&1);v=reversed;}out.push(v);from+=cmd===6?-1:1;}}}throw Error('LZ 종료 마커가 없습니다.');}
// Dynamic-programming compressor: literal, zero, iterate, alternate, forward,
// bit-reversed and reverse references. A changed image must fit its original slot.
function compress(input){const b=bytes(input),n=b.length,cost=new Float64Array(n+1),choice=new Array(n),flip=v=>{let r=0;for(let k=0;k<8;k++)r=(r<<1)|((v>>>k)&1);return r;};cost[n]=1;for(let i=n-1;i>=0;i--){cost[i]=Infinity;const offer=(cmd,len,params)=>{const max=Math.min(len,1024);for(let l=1;l<=max;l++){const head=l<=32?1:2,c=head+(cmd===0?l:params.length)+cost[i+l];if(c<cost[i]){cost[i]=c;choice[i]={cmd,len:l,params};}}};offer(0,n-i,[]);let z=0;while(i+z<n&&b[i+z]===0)z++;if(z)offer(3,z,[]);let run=1;while(i+run<n&&b[i+run]===b[i])run++;if(run>1)offer(1,run,[b[i]]);if(i+1<n){let alt=2;while(i+alt<n&&b[i+alt]===b[i+(alt%2)])alt++;if(alt>2)offer(2,alt,[b[i],b[i+1]]);}const matches=new Map();for(let from=0;from<i;from++){const params=i-from<=128?[128+i-from-1]:[from>>>8,from&255];for(const cmd of [4,5,6]){let l=0;while(l<1024&&i+l<n){const p=from+(cmd===6?-l:l);if(p<0||p>=i+l)break;const v=cmd===5?flip(b[p]):b[p];if(b[i+l]!==v)break;l++;}const key=cmd+':'+params.length;if(l>=3&&l>(matches.get(key)?.len||0))matches.set(key,{cmd,len:l,params});}}for(const m of matches.values())offer(m.cmd,m.len,m.params);}const out=[];for(let i=0;i<n;){const {cmd,len,params}=choice[i],l=len-1;if(len<=32)out.push((cmd<<5)|l);else out.push(0xe0|(cmd<<2)|(l>>>8),l&255);if(cmd===0)out.push(...b.slice(i,i+len));else out.push(...params);i+=len;}out.push(255);return Uint8Array.from(out);}
function decode2bpp(input,width,height,{columnMajor=true}={}){const b=bytes(input);if(width%8||height%8||b.length!==width*height/4)throw Error('2bpp 크기가 맞지 않습니다.');const pixels=new Uint8Array(width*height),tw=width/8,th=height/8;for(let t=0;t<b.length/16;t++){const tx=columnMajor?Math.floor(t/th):t%tw,ty=columnMajor?t%th:Math.floor(t/tw);for(let y=0;y<8;y++)for(let x=0;x<8;x++)pixels[(ty*8+y)*width+tx*8+x]=((b[t*16+y*2]>>>(7-x))&1)|(((b[t*16+y*2+1]>>>(7-x))&1)<<1);}return pixels;}
function encode2bpp(input,width,height,{columnMajor=true}={}){const pixels=bytes(input);if(width%8||height%8||pixels.length!==width*height||pixels.some(x=>x>3))throw Error('픽셀은 0–3이며 크기는 8의 배수여야 합니다.');const out=new Uint8Array(width*height/4),tw=width/8,th=height/8;for(let t=0;t<out.length/16;t++){const tx=columnMajor?Math.floor(t/th):t%tw,ty=columnMajor?t%th:Math.floor(t/tw);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const v=pixels[(ty*8+y)*width+tx*8+x];out[t*16+y*2]|=(v&1)<<(7-x);out[t*16+y*2+1]|=((v>>>1)&1)<<(7-x);}}return out;}
function nameRecords(b){let at=S.moves.names;const result=[];for(let id=1;id<=S.moves.count;id++){const start=at;while(at<b.length&&b[at]!==0x50){if(b[at]>=1&&b[at]<=11)at+=2;else at++;}if(at>=b.length||at-start>S.moves.maxNameBytes)throw Error('기술 이름 테이블이 손상되었습니다.');result.push({id,offset:start,bytes:b.slice(start,at),name:decodeText(b.slice(start,at))});at++;}return{records:result,end:at};}
function parseEvolutionLearnset(b,id){
 integer(id,1,S.evolutions.count,'포켓몬 번호');const pointer=S.evolutions.pointers+(id-1)*2,at=offset(S.evolutions.bank,b[pointer]|(b[pointer+1]<<8)),limit=(S.evolutions.bank+1)*0x4000;let pos=at;
 const read=()=>{if(pos>=limit)throw Error('진화/기술 목록이 ROM 뱅크를 벗어났습니다.');return b[pos++];},evolutions=[],learnset=[];
 while(true){const method=read();if(method===0)break;integer(method,1,5,'진화 방식');const parameter=read(),comparison=method===5?read():undefined,species=read();integer(species,1,251,'진화 종');const row={method,parameter,species};if(comparison!==undefined)row.comparison=comparison;evolutions.push(row);}
 while(true){const level=read();if(level===0)break;integer(level,1,100,'습득 레벨');const move=read();integer(move,1,251,'습득 기술');learnset.push({level,move});}
 return{id,offset:at,pointerOffset:pointer,byteLength:pos-at,evolutions,learnset};
}
function readPalette(b,at,count){range(at,count*2,b.length);const result=[];for(let i=0;i<count;i++){const n=b[at+i*2]|(b[at+i*2+1]<<8);result.push('#'+hex([n&31,(n>>>5)&31,(n>>>10)&31].map(x=>Math.round(x*255/31))));}return result;}
function encodePalette(colors,count){if(!Array.isArray(colors)||colors.length!==count||!colors.every(c=>/^#[a-f\d]{6}$/i.test(c)))throw Error(count+'개의 RGB 색상이 필요합니다.');const out=[];for(const color of colors){const c=unhex(color.slice(1)),r=c.map(x=>Math.round(x*31/255)),word=r[0]|(r[1]<<5)|(r[2]<<10);out.push(word&255,word>>>8);}return Uint8Array.from(out);}
function stringAtIndex(b,at,id){for(let n=1;n<id;n++){while(at<b.length&&b[at]!==0x50)at+=b[at]>=1&&b[at]<=11?2:1;at++;}const start=at;while(at<b.length&&b[at]!==0x50)at+=b[at]>=1&&b[at]<=11?2:1;if(at>=b.length)throw Error('이름 문자열이 손상되었습니다.');return decodeText(b.slice(start,at));}
class Project{
 constructor(original){const initial=bytes(original);privateState.set(this,{original:initial,current:bytes(initial),undo:[],redo:[],moveNameCapacity:nameRecords(initial).end-S.moves.names});}
 get schema(){return S;}
 get size(){return privateState.get(this).current.length;}
 get dirty(){const p=privateState.get(this);return p.current.some((v,i)=>v!==p.original[i]);}
 get canUndo(){return privateState.get(this).undo.length>0;}
 get canRedo(){return privateState.get(this).redo.length>0;}
 readBytes(at,length,{original=false}={}){const p=privateState.get(this);range(at,length,p.current.length);return(original?p.original:p.current).slice(at,at+length);}
 writeBytes(at,input,label='바이트 편집'){const p=privateState.get(this),data=bytes(input);range(at,data.length,p.current.length);return this._commit([{offset:at,bytes:data}],label);}
 _commit(changes,label){const p=privateState.get(this),next=bytes(p.current);for(const c of changes){range(c.offset,c.bytes.length,next.length);next.set(c.bytes,c.offset);}const d=diff(p.current,next);if(!d.length)return false;p.undo.push({label:String(label),changes:d});p.redo=[];p.current=next;return true;}
 undo(){const p=privateState.get(this),edit=p.undo.pop();if(!edit)return false;for(const c of edit.changes)p.current.set(unhex(c.before),c.offset);p.redo.push(edit);return true;}
 redo(){const p=privateState.get(this),edit=p.redo.pop();if(!edit)return false;for(const c of edit.changes)p.current.set(unhex(c.after),c.offset);p.undo.push(edit);return true;}
 reset(){const p=privateState.get(this);return this._commit([{offset:0,bytes:p.original}],'원본으로 되돌리기');}
 rebuild(){const p=privateState.get(this);return this.dirty?fixChecksums(bytes(p.current)):bytes(p.original);}
 manifest(){const p=privateState.get(this);return{format:'designmon-gold-project',version:1,sourceSha256:S.sha256,size:p.original.length,changes:diff(p.original,this.rebuild())};}
 importManifest(m){if(!m||m.format!=='designmon-gold-project'||m.version!==1||m.sourceSha256!==S.sha256||m.size!==S.size||!Array.isArray(m.changes))throw Error('이 원본의 편집 프로젝트가 아닙니다.');const p=privateState.get(this),next=bytes(p.original),used=[];for(const c of m.changes){const a=unhex(c.before),b=unhex(c.after);if(a.length!==b.length||!a.length)throw Error('변경 길이가 맞지 않습니다.');range(c.offset,a.length,next.length);if(used.some(([x,y])=>c.offset<y&&c.offset+a.length>x))throw Error('변경 범위가 겹칩니다.');used.push([c.offset,c.offset+a.length]);if(hex(next.slice(c.offset,c.offset+a.length))!==c.before.toLowerCase())throw Error('원본 바이트가 일치하지 않습니다.');next.set(b,c.offset);}return this._commit([{offset:0,bytes:next}],'프로젝트 불러오기');}
 applyManifest(m){return this.importManifest(m);}
 exportIPS(){const p=privateState.get(this);return makeIPS(p.original,this.rebuild());}
 getPokemon(id){integer(id,1,S.pokemon.count,'포켓몬 번호');const p=privateState.get(this),at=S.pokemon.base+(id-1)*S.pokemon.recordLength,np=S.pokemon.names+(id-1)*S.pokemon.nameLength;const result={id,name:decodeText(p.current.slice(np,np+S.pokemon.nameLength)),offset:at,nameOffset:np,tmhm:Array.from(p.current.slice(at+24,at+32))};for(const [key,rel]of Object.entries(S.pokemonFields))result[key]=p.current[at+rel];return result;}
 setPokemon(id,patch){const record=this.getPokemon(id),changes=[];for(const [key,value]of Object.entries(patch)){if(key==='name'){const b=encodeText(value);if(b.includes(0x50))throw Error('이름에 종료 코드를 넣을 수 없습니다.');changes.push({offset:record.nameOffset,bytes:encodeText(value,{length:S.pokemon.nameLength})});}else if(key==='tmhm'){const b=bytes(value);if(b.length!==8)throw Error('TM/HM 필드는 8바이트입니다.');changes.push({offset:record.offset+24,bytes:b});}else if(Object.hasOwn(S.pokemonFields,key)){integer(value,0,255,key);changes.push({offset:record.offset+S.pokemonFields[key],bytes:Uint8Array.of(value)});}else throw Error('알 수 없는 종 필드: '+key);}return this._commit(changes,'포켓몬 '+id+' 편집');}
 getMove(id){integer(id,1,S.moves.count,'기술 번호');const p=privateState.get(this),at=S.moves.base+(id-1)*S.moves.recordLength,n=nameRecords(p.current).records[id-1],result={id,name:n.name,offset:at,nameOffset:n.offset};for(const [key,rel]of Object.entries(S.moveFields))result[key]=p.current[at+rel];return result;}
 setMove(id,patch){const record=this.getMove(id),p=privateState.get(this),changes=[];for(const[key,value]of Object.entries(patch)){if(key==='name'){const names=nameRecords(p.current).records.map(r=>r.bytes),name=encodeText(value);if(name.length>S.moves.maxNameBytes||name.includes(0x50))throw Error('기술 이름은 종료 코드 없이 16바이트 이하입니다.');names[id-1]=name;const combined=Uint8Array.from(names.flatMap(b=>[...b,0x50]));if(combined.length>p.moveNameCapacity)throw Error('기술 이름 테이블 공간 부족: '+combined.length+' / '+p.moveNameCapacity+'바이트');const b=new Uint8Array(p.moveNameCapacity).fill(0x50);b.set(combined);changes.push({offset:S.moves.names,bytes:b});}else if(Object.hasOwn(S.moveFields,key)){integer(value,0,key==='pp'?40:255,key);changes.push({offset:record.offset+S.moveFields[key],bytes:Uint8Array.of(value)});}else throw Error('알 수 없는 기술 필드: '+key);}return this._commit(changes,'기술 '+id+' 편집');}
 getEvolutionLearnset(id){const p=privateState.get(this),current=parseEvolutionLearnset(p.current,id),original=parseEvolutionLearnset(p.original,id);return{...current,capacity:original.byteLength};}
 setEvolutionLearnset(id,patch){
  const data=this.getEvolutionLearnset(id),baseline=parseEvolutionLearnset(privateState.get(this).original,id);if(data.offset!==baseline.offset||data.byteLength!==baseline.byteLength)throw Error('진화 목록의 원본 포인터 또는 슬롯 길이가 변경되었습니다. 전체 소스에서 편집하세요.');if(!patch||Object.keys(patch).some(k=>!['evolutions','learnset'].includes(k)))throw Error('진화/레벨업 기술 필드를 확인하세요.');const evos=patch.evolutions??data.evolutions,learn=patch.learnset??data.learnset;if(!Array.isArray(evos)||!Array.isArray(learn))throw Error('진화와 기술은 배열이어야 합니다.');const out=[];
  for(const e of evos){integer(e.method,1,5,'진화 방식');integer(e.species,1,251,'진화 종');integer(e.parameter,0,255,'진화 조건');if([1,5].includes(e.method))integer(e.parameter,1,100,'진화 레벨');if(e.method===4)integer(e.parameter,1,3,'친밀도 시간대');out.push(e.method,e.parameter);if(e.method===5)out.push(integer(e.comparison,1,3,'공격/방어 비교'));out.push(e.species);}out.push(0);
  for(const m of learn){integer(m.level,1,100,'습득 레벨');integer(m.move,1,251,'기술 번호');out.push(m.level,m.move);}out.push(0);
  if(out.length>data.capacity)throw Error('진화/레벨업 기술 공간 부족: '+out.length+' / '+data.capacity+'바이트');const b=this.readBytes(data.offset,data.capacity);b.set(out);return this.writeBytes(data.offset,b,'포켓몬 '+id+' 진화/레벨업 기술');
 }
 getTrainerPalette(id){integer(id,1,S.trainers.count,'트레이너 번호');return['#ffffff',...readPalette(privateState.get(this).current,S.trainers.palettes+id*4,2),'#000000'];}
 setTrainerPalette(id,colors){integer(id,1,S.trainers.count,'트레이너 번호');encodePalette(colors,4);return this.writeBytes(S.trainers.palettes+id*4,encodePalette(colors.slice(1,3),2),'트레이너 '+id+' 팔레트');}
 getTrainerSprite(id){integer(id,1,S.trainers.count,'트레이너 번호');const b=privateState.get(this).current,ptr=S.trainers.pointers+(id-1)*3,bank=S.picBankMap[b[ptr]]??b[ptr],at=offset(bank,b[ptr+1]|(b[ptr+2]<<8)),decoded=decompress(b,at);return{id,name:stringAtIndex(b,S.trainers.names,id),width:56,height:56,offset:at,pointerOffset:ptr,bank,compressedLength:decoded.consumed,tiles:decoded.bytes,pixels:decode2bpp(decoded.bytes,56,56),palette:this.getTrainerPalette(id)};}
 setTrainerSprite(id,pixels){const sprite=this.getTrainerSprite(id),p=privateState.get(this),ptr=sprite.pointerOffset;if(hex(p.current.slice(ptr,ptr+3))!==hex(p.original.slice(ptr,ptr+3)))throw Error('트레이너 그림의 원본 포인터가 변경되었습니다. 전체 소스에서 편집하세요.');const baseline=decompress(p.original,sprite.offset),capacity=baseline.consumed;if(sprite.compressedLength!==capacity||sprite.tiles.length!==baseline.bytes.length)throw Error('트레이너 그림의 원본 슬롯 길이가 변경되었습니다. 전체 소스에서 편집하세요.');const encoded=encode2bpp(pixels,56,56);if(hex(encoded)===hex(sprite.tiles))return false;const packed=compress(encoded);if(packed.length>capacity)throw Error('트레이너 스프라이트 공간 부족: '+packed.length+' / '+capacity+'바이트');const patch=this.readBytes(sprite.offset,capacity);patch.set(packed);return this.writeBytes(sprite.offset,patch,'트레이너 '+id+' 스프라이트');}
 getOverworldPalette(id,time=1){integer(id,0,7,'맵 팔레트');integer(time,0,3,'시간대');return readPalette(privateState.get(this).current,S.overworld.palettes+time*64+id*8,4);}
 setOverworldPalette(id,colors,time=1){integer(id,0,7,'맵 팔레트');integer(time,0,3,'시간대');return this.writeBytes(S.overworld.palettes+time*64+id*8,encodePalette(colors,4),'맵 팔레트 '+id+' 시간대 '+time);}
 getOverworldSprite(id,time=1){
  integer(id,1,S.overworld.count,'맵 캐릭터 번호');const b=privateState.get(this).current,ptr=S.overworld.headers+(id-1)*S.overworld.recordLength,bank=b[ptr+3],at=offset(bank,b[ptr]|(b[ptr+1]<<8)),kind=b[ptr+4],paletteId=b[ptr+5],standingBytes=b[ptr+2];integer(kind,1,3,'맵 스프라이트 종류');if(![64,192].includes(standingBytes))throw Error('맵 스프라이트 타일 크기가 올바르지 않습니다.');const byteLength=standingBytes*(kind===1?2:1),tiles=b.slice(at,at+byteLength),height=byteLength/4,frameCount=height/16;
  return{id,width:16,height,frameCount,kind,offset:at,headerOffset:ptr,bank,paletteId,byteLength,tiles,pixels:decode2bpp(tiles,16,height,{columnMajor:false}),palette:this.getOverworldPalette(paletteId,time),layout:'runtime-frame-sheet'};
 }
 setOverworldSprite(id,pixels){const sprite=this.getOverworldSprite(id),encoded=encode2bpp(pixels,sprite.width,sprite.height,{columnMajor:false});return this.writeBytes(sprite.offset,encoded,'맵 캐릭터 '+id+' 스프라이트');}
 getPalette(id,shiny=false){integer(id,1,251,'포켓몬 번호');const b=privateState.get(this).current,at=S.pokemon.palettes+id*8+(shiny?4:0),colors=['#ffffff'];for(let i=0;i<2;i++){const n=b[at+i*2]|(b[at+i*2+1]<<8),rgb=[n&31,(n>>>5)&31,(n>>>10)&31].map(x=>Math.round(x*255/31));colors.push('#'+hex(rgb));}colors.push('#000000');return colors;}
 setPalette(id,colors,shiny=false){integer(id,1,251,'포켓몬 번호');if(!Array.isArray(colors)||colors.length!==4||!colors.every(c=>/^#[a-f\d]{6}$/i.test(c)))throw Error('4개의 RGB 색상이 필요합니다.');const out=[];for(const color of colors.slice(1,3)){const c=unhex(color.slice(1)),r=c.map(x=>Math.round(x*31/255)),word=r[0]|(r[1]<<5)|(r[2]<<10);out.push(word&255,word>>>8);}return this.writeBytes(S.pokemon.palettes+id*8+(shiny?4:0),out,'포켓몬 '+id+' 팔레트');}
 getSprite(id,side='front',unownLetter=1){const mon=this.getPokemon(id);if(!['front','back'].includes(side))throw Error('front 또는 back 스프라이트를 선택하세요.');integer(unownLetter,1,26,'안농 문자');const p=privateState.get(this),table=id===201?S.pokemon.unownPointers:S.pokemon.pointers,index=id===201?unownLetter:id,ptr=table+(index-1)*6+(side==='back'?3:0),rawBank=p.current[ptr],bank=S.picBankMap[rawBank]??rawBank,at=offset(bank,p.current[ptr+1]|(p.current[ptr+2]<<8)),decoded=decompress(p.current,at),width=side==='back'?48:(mon.picSize&15)*8,height=side==='back'?48:(mon.picSize>>>4)*8;return{id,side,unownLetter,width,height,offset:at,pointerOffset:ptr,bank,compressedLength:decoded.consumed,tiles:decoded.bytes,pixels:decode2bpp(decoded.bytes,width,height),palette:this.getPalette(id)};}
 setSprite(id,side,pixels,unownLetter=1){const original=this.getSprite(id,side,unownLetter),p=privateState.get(this),ptr=original.pointerOffset;if(hex(p.current.slice(ptr,ptr+3))!==hex(p.original.slice(ptr,ptr+3)))throw Error('몬스터 그림의 원본 포인터가 변경되었습니다. 전체 소스에서 편집하세요.');const baseline=decompress(p.original,original.offset),capacity=baseline.consumed,dimension=S.pokemon.base+(id-1)*S.pokemon.recordLength+17;if(original.compressedLength!==capacity||original.tiles.length!==baseline.bytes.length||p.current[dimension]!==p.original[dimension])throw Error('몬스터 그림의 원본 슬롯 길이 또는 치수가 변경되었습니다. 전체 소스에서 편집하세요.');const encoded=encode2bpp(pixels,original.width,original.height);if(hex(encoded)===hex(original.tiles))return false;const packed=compress(encoded);if(packed.length>capacity)throw Error('원본 스프라이트 공간 부족: '+packed.length+' / '+capacity+'바이트. 다른 데이터는 덮어쓰지 않았습니다.');const patch=p.current.slice(original.offset,original.offset+capacity);patch.set(packed);return this.writeBytes(original.offset,patch,'포켓몬 '+id+' '+side+' 스프라이트');}
}
async function create(input){const b=bytes(input);if(b.length!==S.size)throw Error('한국어 골드 원본은 2,097,152바이트여야 합니다.');const actual=await hash(b);if(actual!==S.sha256)throw Error('지원하는 한국어 골드 원본의 SHA-256과 다릅니다. 수정본은 원본과 편집 프로젝트로 불러오세요.');return new Project(b);}
return{schema:S,create,hash,encodeText,decodeText,checksum,offset,makeIPS,applyIPS,compress,decompress,decode2bpp,encode2bpp,hex,unhex};
});
