(function(){
  'use strict';
  const D=DesignmonData,C=DesignmonCore,A=DesignmonArt,$=id=>document.getElementById(id);
  const canvas=$('world'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
  let state=null,mode='title',returnMode='explore',dialogue=null,modalKind='',keys=new Set(),pendingMove=null,path=[],pathNPC=null,lastMove=0,walkingUntil=0,cam={x:70,y:110},toastTimer,busy=false,audio=null;
  const itemNames={coffee:'따뜻한 커피',snack:'함께 먹는 간식',notebook:'합의 노트',break:'충분한 휴식권'};
  const storage={getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)};
  const loaded=C.load(storage);$('continue').disabled=!loaded.ok;if(loaded.error)$('saveError').textContent='저장 기록을 읽지 못했습니다. 메뉴에서 원본을 내보내 보관할 수 있습니다.';
  const demo={...C.start('typo'),map:'town',x:17,y:13,dir:'right'};
  function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
  function tone(note=440){if(!state?.settings.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=note;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.13);}catch{}}
  function clearInput(){keys.clear();pendingMove=null;path=[];pathNPC=null;walkingUntil=0;}
  function setMode(next){mode=next;clearInput();$('title').hidden=next!=='title';$('dialog').hidden=next!=='dialog';$('battle').hidden=!state?.battle;$('modal').hidden=!['choose','modal'].includes(next);$('interactHint').hidden=true;}
  function autosave(){if(!state||state.battle)return;const result=C.save(state,storage);if(!result.ok)toast('저장하지 못했습니다: '+result.error);else $('continue').disabled=false;}
  function saveManual(){if(!state){toast('모험을 시작한 뒤 저장할 수 있습니다.');return;}if(state.battle){toast('의뢰를 마친 뒤 저장할 수 있습니다.');return;}const r=C.save(state,storage);toast(r.ok?'모험을 저장했습니다.':('저장하지 못했습니다: '+r.error));}
  function hud(){const s=state||demo,m=D.maps[s.map];$('location').innerHTML='<span class="location-dot"></span><div><strong>'+m.name+'</strong><small>'+m.subtitle+'</small></div>';$('coins').textContent=state?state.coins.toLocaleString()+' C':'—';$('partyList').innerHTML=state?state.team.map(id=>{const mon=C.mon(id);return '<div class="mini-mon"><img src="'+A.icon(id)+'" alt="'+mon.name+'"><div><strong>'+mon.name+'</strong><small>Lv.'+state.levels[id]+'</small><div class="bar"><i style="width:'+100*state.condition[id]/C.maxHp(state,id)+'%"></i></div></div></div>';}).join(''):'<p class="quiet">아직 만나지 못한 가능성들.</p>';
    const p=state&&C.nextProject(state);$('objectiveTitle').textContent=!state?'첫 동료를 만나보세요':p?p.name:'조금 덜 무서워졌다';$('objectiveText').textContent=!state?'시작 스튜디오에서 첫 동료와 함께해요.':p?'마을 남동쪽 클라이언트 공방에서 '+p.client+'와 이야기해 보세요.': '세 건의 의뢰를 마쳤어요. 동료들과 숲을 더 걷거나 새로운 팀을 꾸려보세요.';$('questTrack').innerHTML=D.projects.map(p=>'<span class="'+(state?.completed.includes(p.id)?'done':'')+'"></span>').join('');$('sound').textContent='♪ '+(state?.settings.sound?'ON':'OFF');}
  function say(speaker,lines,after){dialogue={speaker,lines,index:0,after};setMode('dialog');renderDialog();}
  function renderDialog(){$('dialog').innerHTML='<div class="speaker">'+dialogue.speaker+'</div><p>'+dialogue.lines[dialogue.index]+'</p><button class="primary" data-action="advance">'+(dialogue.index<dialogue.lines.length-1?'다음':'계속')+' <span>↵</span></button>';}
  function advance(){if(!dialogue)return;tone(520);dialogue.index++;if(dialogue.index<dialogue.lines.length){renderDialog();return;}const after=dialogue.after;dialogue=null;setMode('explore');if(after)after();hud();}
  function newGame(){const existing=C.load(storage);if(existing.ok){openModal('confirmNew');return;}intro();}
  function intro(){state=null;setMode('explore');say('어느 늦은 밤',['모니터 앞에서 눈을 감았다. 아직 끝내지 못한 작업과, 잘할 수 있을지 모를 내일을 두고.','눈을 뜬 곳에는 처음 보는 마을이 있었다. 이곳에서는 경험과 태도가 작은 동료의 모습으로 나타난다고 했다.','“완벽한 준비는 필요 없어요. 지금 당신에게 필요한 동료부터 만나볼까요?”'],choose);}
  function choose(){setMode('choose');$('modal').innerHTML='<div class="modal-head"><h2>첫 번째 동료를 만나세요</h2></div><p>가장 강한 동료보다, 지금 당신에게 맞는 관점을 골라보세요.</p><div class="starter-grid">'+D.starters.map(id=>{const m=C.mon(id);return '<article class="mon-card"><img src="'+A.icon(id)+'" alt="'+m.name+'"><h3>'+m.name+'</h3><small>'+m.type+' · '+m.role+'</small><p>'+m.desc+'</p><button class="primary" data-action="starter" data-id="'+id+'">함께하기 →</button></article>';}).join('')+'</div>';}
  function pickStarter(id){state=C.start(id);autosave();hud();say('스튜디오의 기록자',[C.mon(id).name+'이 당신의 첫 동료가 되었다. 이 아이의 컨디션은 당신의 멘탈, 체력, 집중력을 함께 뜻한다.','마을 남동쪽 공방에서 첫 의뢰를 받아보자. 진척도 100%와 필요한 합의를, 기한 안에 채우면 납품할 수 있다.','힘이 들면 북동쪽의 쉼표를 찾아가자. 회복할 줄 아는 사람이 오래 살아남으니까.'],()=>setMode('explore'));}
  function talk(n){if(!state||mode!=='explore')return;clearInput();tone(620);if(n.id==='mentor')say(n.name,['이곳의 배틀은 외주 한 건이야. 턴은 작업과 피드백의 한 사이클이지.','설명과 범위를 먼저 맞추면 나중의 수정을 줄일 수 있어. 제출만 서두르는 것이 항상 가장 빠르지는 않아.']);
    else if(n.id==='rest'){state=C.heal(state);autosave();hud();say(n.name,['모든 동료의 컨디션을 회복했어요. 잠깐 쉬었다는 이유로 뒤처지는 건 아니에요.','도구가 없어도 언제든 들러요. 충분히 쉬고 다시 시작하면 돼요.']);}
    else if(n.id==='shop')openModal('shop');
    else if(n.id==='guide')say(n.name,['공방은 마을 남동쪽의 보랏빛 지붕 건물이야. 책방지기부터 만나보면 돼.','동쪽 레퍼런스 숲에서는 작은 연습 의뢰를 할 수 있어. 경험이 쌓이면 새로운 동료도 만날 거야.']);
    else if(n.id==='fieldGuide')say(n.name,['디자인몬은 붙잡는 존재가 아니라, 경험이 쌓여 나타나는 동료야.','서로 다른 프로젝트를 지나면 새로운 관점을 얻게 되지. 정답 파티는 없어.']);
    else if(n.id==='practice')brief('practice');
    else if(D.projects.some(p=>p.id===n.id)){if(state.completed.includes(n.id))say(n.name,['함께 마무리한 작업, 잘 쓰고 있어요. 다음 작업에서도 당신의 기준을 잃지 않기를 바랄게요.']);else if(C.nextProject(state)?.id!==n.id)say(n.name,['먼저 '+C.nextProject(state).client+'와 작은 작업을 마쳐보세요. 그 경험이 이번 의뢰에도 도움이 될 거예요.']);else brief(n.id);}}
  function interact(){if(mode==='dialog'){advance();return;}if(mode!=='explore'||!state)return;const n=C.nearby(state);if(n)talk(n);else toast('인물 앞에서 Enter를 누르거나 인물을 클릭해 보세요.');}
  function brief(id){openModal('brief:'+id);}
  function openModal(kind){if(mode==='dialog'||mode==='choose')return;returnMode=state?.battle?'battle':state?'explore':'title';modalKind=kind;setMode('modal');renderModal();}
  function closeModal(){setMode(returnMode);if(state?.battle)renderBattle();else hud();}
  function monCards(){return D.mons.map(m=>{const owned=state.owned.includes(m.id);return '<article class="mon-card '+(!owned?'locked':'')+'"><img src="'+A.icon(m.id)+'" alt="'+m.name+'"><h3>'+m.name+'</h3><span class="type-tag">'+m.type+'</span><p>'+m.role+'</p>'+(owned?'<small>Lv.'+state.levels[m.id]+' · 컨디션 '+state.condition[m.id]+'/'+C.maxHp(state,m.id)+'</small><div class="slot-buttons">'+[0,1,2].map(i=>'<button data-action="slot" data-id="'+m.id+'" data-slot="'+i+'" '+(i>state.team.length?'disabled':'')+'>'+ (state.team[i]===m.id?'✓ ':'')+(i+1)+'번</button>').join('')+'</div>':'<small>프로젝트 경험으로 만날 동료</small>')+'</article>';}).join('');}
  function renderModal(){let title='',body='';const kind=modalKind;
    if(kind.startsWith('brief:')){const p=C.project(kind.split(':')[1]);title=p.name;body='<span class="type-tag">'+p.client+' · '+p.tag+'</span><p>'+p.brief+'</p><div class="journal-item"><h3>함께 끝내기 위한 약속</h3><p>기한: '+p.deadline+'턴 / 진척: 100% / 합의: '+p.goal+' 이상</p><p>중요한 기준: '+p.need+'</p><p>보상: '+p.reward+' 코인'+(p.badge?' · '+p.badge:'')+'</p></div><p>의뢰 중에는 한 번의 행동마다 작업과 피드백이 이어집니다. 상대를 쓰러뜨리는 것이 아니라 프로젝트를 마치는 것이 목표입니다.</p><button class="primary" data-action="begin" data-id="'+p.id+'">의뢰 시작하기 →</button>';}
    else if(kind==='confirmNew'){title='새로운 모험을 시작할까요?';body='<p>첫 동료를 선택하면 현재 저장 기록이 새 모험으로 바뀝니다. 기존 기록을 남기려면 먼저 내보내세요.</p><div class="menu-actions"><button data-action="export">기록 내보내기</button><button data-action="newConfirmed">새 모험 시작</button></div>';}
    else if(kind==='team'){title='함께하는 동료';body=state?'<p>활성 팀은 세 동료까지. 번호를 눌러 위치를 바꾸거나 대기 중인 동료를 팀에 넣으세요.</p><div class="team-grid">'+monCards()+'</div>':'<p>모험을 시작하면 경험을 통해 동료를 만나게 됩니다.</p>';}
    else if(kind==='journal'){title='의뢰 노트';body=(state?.completed.length===3?'<div class="end-banner">첫 챕터 완료 · 조금 덜 무서워졌다.<br><small>동료들과 더 돌아다니거나 숲에서 팀 조합을 시험해보세요.</small></div>':'')+D.projects.map((p,i)=>'<article class="journal-item"><span class="done">'+(state?.completed.includes(p.id)?'✓ 납품 완료':C.nextProject(state||{completed:[]})?.id===p.id?'진행 가능':'앞선 의뢰 후')+'</span><h3>0'+(i+1)+' / '+p.name+'</h3><p>'+p.client+' · '+p.brief+'</p><p>'+p.deadline+'턴 안에 진척 100%, 합의 '+p.goal+' · '+p.badge+'</p></article>').join('')+'<p>마을 남동쪽 클라이언트 공방에서 의뢰인을 만나세요. 동쪽 숲에는 반복 가능한 연습 의뢰가 있습니다.</p>';}
    else if(kind==='shop'){title='도구 상점';body='<p>남은 지원금 '+state.coins+' C · 도구는 의뢰 중 사용할 수 있어요. 라운지의 회복은 무료입니다.</p>'+Object.entries(itemNames).map(([id,name],i)=>'<div class="shop-row"><div><strong>'+name+' × '+state.items[id]+'</strong><p>'+['현재 동료 컨디션 +35','팀 전체 컨디션 +18','상태이상 해제 · 합의 +10','현재 동료 완전 회복'][i]+'</p></div><button class="primary" data-action="buy" data-id="'+id+'" '+(state.coins<[25,30,35,65][i]?'disabled':'')+'>'+[25,30,35,65][i]+' C</button></div>').join('');}
    else if(kind==='items'){title='작업 도구';body=Object.entries(itemNames).map(([id,name],i)=>'<div class="shop-row"><div><strong>'+name+' × '+state.items[id]+'</strong><p>'+['현재 동료 컨디션 +35','팀 전체 컨디션 +18','상태이상 해제 · 합의 +10','현재 동료 완전 회복'][i]+'</p></div><button class="primary" data-action="item" data-id="'+id+'" '+(!state.items[id]?'disabled':'')+'>사용 · 1턴</button></div>').join('');}
    else if(kind==='battleTeam'){title='다른 관점으로 이어가기';body=state.team.map(id=>'<div class="shop-row"><div><strong>'+C.mon(id).name+'</strong><p>컨디션 '+state.condition[id]+'/'+C.maxHp(state,id)+' · '+C.mon(id).type+'</p></div><button class="primary" data-action="switch" data-id="'+id+'" '+(id===state.battle.active||state.condition[id]===0?'disabled':'')+'>교체 · 1턴</button></div>').join('');}
    else if(kind==='help'){title='이곳에서 모험하는 법';body='<div class="journal-item"><h3>탐험과 만남</h3><p>방향키 / WASD로 이동, Enter / Z로 대화합니다. 인물이나 땅을 클릭하면 그곳까지 걸어가요. Esc / X는 닫기, M은 메뉴입니다.</p></div><div class="journal-item"><h3>작업과 피드백</h3><p>진척 100%와 필요한 합의를 기한 안에 채우면 납품 완료! 설명은 합의를 높이고 피드백 소모를 줄입니다. 범위 정의는 수정과 방향 변경을 예방합니다.</p><p>수정 요청: 지속 소모 / 일정 압박: 속도 저하 / 요구사항 변경: 명중률 저하 / 야근: 진척 상승과 소모 / 번아웃 징후: 제출 실패 가능성.</p></div><div class="journal-item"><h3>회복과 저장</h3><p>의뢰 실패 후에는 회복해 다시 도전할 수 있습니다. 마을 북동쪽 쉼표 라운지의 회복은 무료입니다. 동료는 프로젝트 경험으로 합류합니다.</p><p>맵 이동과 의뢰 완료 시 자동 저장합니다. 의뢰 중간은 저장하지 않습니다. 다른 브라우저나 기기로 옮기려면 메뉴에서 기록을 내보내세요.</p></div>';}
    else {title='모험 메뉴';body='<p>기록은 이 브라우저에 저장됩니다. 브라우저 데이터 삭제에 대비해 파일로 보관할 수 있습니다.</p><div class="menu-actions"><button data-action="save">저장</button><button data-action="export">기록 내보내기</button><button data-action="import">기록 가져오기</button><button data-action="help">플레이 가이드</button><button data-action="title">타이틀로</button></div><p>게임 원작 ROM 실험은 상단의 ‘골드 ROM 플레이’에서 별도로 실행할 수 있습니다.</p>';}
    $('modal').innerHTML='<div class="modal-head"><h2>'+title+'</h2><button class="close" data-action="close" aria-label="닫기">×</button></div>'+body;
  }
  function renderBattle(){if(!state?.battle)return;const b=state.battle,p=C.project(b.project),m=C.mon(b.active);$('battle').hidden=false;
    if(b.result){const won=b.result==='won';$('battle').innerHTML='<div class="result-card"><div class="result-symbol">'+(won?'✦':'☾')+'</div><span class="eyebrow">'+(won?'PROJECT COMPLETED':'TIME TO RECOVER')+'</span><h2>'+(won?'함께 끝냈다.':'잠깐, 쉬어가도 괜찮아.')+'</h2><p>'+p.name+'<br>'+(won?'한 번의 프로젝트가 당신의 경험이 되었습니다.':'끝이 아니라, 회복이 필요한 순간입니다.<br>동료들의 컨디션을 회복하고 다시 시작할 수 있어요.')+'</p><div class="reward">'+(won?p.reward+' C · 팀 경험치 +35'+(p.recruits.length?'<br>새로운 관점을 가진 동료들이 합류했습니다.':''):'코인과 동료는 그대로 유지됩니다. 쉼표 라운지로 돌아갑니다.')+'</div><button class="primary" data-action="finish">모험으로 돌아가기 →</button></div>';return;}
    const event=D.feedback[p.pattern[(b.turn-1)%p.pattern.length]];
    $('battle').innerHTML='<div class="battle-top"><div><span class="eyebrow">PROJECT / '+p.client+'</span><h2>'+p.name+'</h2></div><div class="deadline">남은 작업 사이클<br><strong>'+(p.deadline-b.turn+1)+'</strong> / '+p.deadline+'</div></div><div class="arena"><div class="combatant"><img src="'+A.icon(m.id)+'" alt="'+m.name+'"><strong>'+m.name+' <small>Lv.'+state.levels[m.id]+'</small></strong></div><div class="combatant"><span class="client-icon" aria-hidden="true">'+(p.id==='book'?'▤':p.id==='cafe'?'☕':p.id==='guild'?'⌘':'✎')+'</span><strong>'+p.client+'</strong><small>'+p.need+'</small></div></div><div class="meters"><div class="meter"><label>프로젝트 진척 <b>'+b.progress+'%</b></label><div class="bar"><i style="width:'+b.progress+'%"></i></div></div><div class="meter trust"><label>합의 <b>'+b.agreement+' / '+p.goal+'</b></label><div class="bar"><i style="width:'+b.agreement+'%"></i></div></div><div class="meter focus"><label>컨디션 <b>'+state.condition[m.id]+'</b></label><div class="bar"><i style="width:'+100*state.condition[m.id]/C.maxHp(state,m.id)+'%"></i></div></div></div><div class="telegraph">다음 피드백 · '+event.line+'</div><div class="statuses">'+Object.entries(b.status).map(([k,v])=>'<span class="status-pill" title="'+D.statuses[k].desc+'">'+D.statuses[k].name+' '+v.remaining+'턴</span>').join('')+(b.scope?'<span class="status-pill">범위 합의 '+b.scope+'턴</span>':'')+'</div><div class="battle-actions"><button data-action="combat" data-type="submit"><b>작업물 제출</b><small>진척을 쌓는다</small></button><button data-action="combat" data-type="explain"><b>선택의 이유 설명</b><small>합의 ↑ · 부담 ↓</small></button><button data-action="combat" data-type="scope"><b>범위 함께 정하기</b><small>수정·변경 예방</small></button>'+m.skills.map(id=>'<button data-action="skill" data-id="'+id+'" title="'+D.skills[id].detail+'"><b>'+D.skills[id].name+'</b><small>'+D.skills[id].detail+'</small></button>').join('')+'<button data-action="combat" data-type="rest"><b>한 템포 쉬기</b><small>컨디션 +27</small></button></div><div class="battle-extra"><button data-action="items">도구 사용</button><button data-action="battleTeam">동료 교체</button><button data-action="withdraw">의뢰 중단</button></div><div class="battle-log" role="status" aria-live="polite">'+b.log.slice(-3).map(l=>'<p>'+l+'</p>').join('')+'</div>';
  }
  function combat(action){if(busy||!state?.battle||state.battle.result)return;busy=true;setMode('battle');state=C.act(state,action);renderBattle();hud();tone(action.type==='submit'?380:580);setTimeout(()=>{busy=false;},220);}
  function finish(){if(!state?.battle?.result)return;const completed=state.battle.result==='won';state=C.finish(state);setMode('explore');autosave();hud();if(completed&&state.completed.length===3&&!state.flags.ending){state.flags.ending=true;autosave();say('현실로 이어지는 기록',['처음엔 클라이언트의 말 한마디가 모든 걸 무너뜨리는 것 같았다. 이제는 무엇을 묻고, 어디까지 합의하고, 언제 쉬어야 할지 조금 알 것 같다.','디자인 실력은 재능이 아니라, 견뎌낸 프로젝트의 총합이다. 완벽해진 것은 아니지만, 조금 덜 무서워졌다.','첫 번째 챕터를 마쳤습니다. 여덟 동료와 자유롭게 탐험하거나 레퍼런스 숲에서 다른 팀을 시험해 보세요.']);}}
  function exportSave(){try{const raw=state&&!state.battle?JSON.stringify(C.validate(state),null,2):storage.getItem('designmon-adventure-v1');if(!raw){toast('내보낼 기록이 없습니다.');return;}const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='designmon-adventure-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('기록 파일을 내보냈습니다.');}catch(e){toast('내보내기 실패: '+e.message);}}
  function action(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
    if(a==='new')newGame();else if(a==='newConfirmed'){setMode('title');intro();}else if(a==='starter')pickStarter(b.dataset.id);else if(a==='advance')advance();
    else if(a==='continue'){const r=C.load(storage);if(r.ok){state=r.state;setMode('explore');hud();toast('기록한 모험을 이어갑니다.');}else toast('기록을 읽지 못했습니다: '+(r.error||'저장 없음'));}
    else if(a==='close'||a==='back'){if(mode==='modal')closeModal();else if(mode==='dialog')advance();}
    else if(a==='interact')interact();else if(a==='save')saveManual();else if(a==='export')exportSave();else if(a==='import'){if(state?.battle){toast('의뢰를 마친 뒤 기록을 가져올 수 있습니다.');return;}$('importSave').click();}
    else if(a==='title'){if(state?.battle){toast('의뢰를 마치거나 중단한 뒤 돌아갈 수 있습니다.');return;}autosave();setMode('title');const r=C.load(storage);$('continue').disabled=!r.ok;}
    else if(a==='begin'){try{state=C.begin(state,b.dataset.id);setMode('battle');renderBattle();hud();}catch(err){toast(err.message);}}
    else if(a==='combat')combat({type:b.dataset.type});else if(a==='skill')combat({type:'skill',id:b.dataset.id});else if(a==='item')combat({type:'item',id:b.dataset.id});else if(a==='switch')combat({type:'switch',id:b.dataset.id});else if(a==='withdraw')openModal('withdrawConfirm');
    else if(a==='finish')finish();else if(a==='slot'){state=C.swap(state,b.dataset.id,Number(b.dataset.slot));autosave();renderModal();hud();}
    else if(a==='buy'){state=C.buy(state,b.dataset.id);autosave();renderModal();hud();tone(720);}
    else if(['team','journal','menu','help','items','battleTeam'].includes(a)){if(state?.battle&&['team','journal','menu'].includes(a)){toast('의뢰 중에는 배틀 안의 동료·도구 버튼을 사용하세요.');return;}openModal(a);}
  }
  // Keep withdrawal explicit so accidental taps do not abandon a project.
  const originalRenderModal=renderModal;renderModal=function(){if(modalKind==='withdrawConfirm'){$('modal').innerHTML='<div class="modal-head"><h2>이번 의뢰를 잠시 멈출까요?</h2><button class="close" data-action="close" aria-label="닫기">×</button></div><p>의뢰 진행은 초기화됩니다. 동료와 코인은 유지되며, 회복한 뒤 다시 도전할 수 있습니다.</p><button class="primary" data-action="combat" data-type="withdraw">중단하고 쉬기</button>';return;}originalRenderModal();};
  document.addEventListener('click',action);
  $('sound').onclick=()=>{if(!state){toast('모험을 시작한 뒤 효과음을 켤 수 있어요.');return;}state.settings.sound=!state.settings.sound;tone(660);hud();autosave();};
  $('importSave').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>100000)throw Error('저장 파일이 너무 큽니다.');const imported=C.validate(JSON.parse(await file.text()));openModal('importConfirm');$('modal').innerHTML='<div class="modal-head"><h2>기록을 가져올까요?</h2><button class="close" data-action="close" aria-label="닫기">×</button></div><p>동료 '+imported.owned.length+'종 · 완료한 의뢰 '+imported.completed.length+'건. 현재 기록을 이 파일로 바꿉니다.</p><button id="confirmImport" class="primary">이 기록으로 이어하기</button>';$('confirmImport').onclick=()=>{const r=C.save(imported,storage);if(!r.ok){toast('기록 저장 실패: '+r.error);return;}state=imported;setMode('explore');hud();toast('기록을 가져왔습니다.');};}catch(err){toast('기록을 가져오지 못했습니다: '+err.message);}};
  const directions={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};
  window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.tagName==='INPUT')return;if(directions[e.code]){e.preventDefault();if(mode==='explore'){path=[];pathNPC=null;keys.add(directions[e.code]);if(!e.repeat)pendingMove=directions[e.code];}else if(!e.repeat){const panel=mode==='dialog'?$('dialog'):mode==='battle'?$('battle'):mode==='title'?$('title'):$('modal'),buttons=[...panel.querySelectorAll('button:not(:disabled)')];const i=buttons.indexOf(document.activeElement),delta=['up','left'].includes(directions[e.code])?-1:1;if(buttons.length)buttons[(i+delta+buttons.length)%buttons.length].focus();}return;}
    if(e.repeat)return;if(['Enter','KeyZ','Space'].includes(e.code)){if(e.target.tagName==='BUTTON'&&(e.code==='Enter'||e.code==='Space'))return;e.preventDefault();if(mode==='dialog')advance();else if(mode==='explore')interact();else if(mode==='title')newGame();else{const panel=mode==='battle'?$('battle'):$('modal');const focused=panel.contains(document.activeElement)&&document.activeElement.tagName==='BUTTON'?document.activeElement:panel.querySelector('button:not(:disabled)');focused?.click();}}
    else if(['Escape','KeyX'].includes(e.code)){e.preventDefault();if(mode==='modal')closeModal();else if(mode==='dialog')advance();else if(mode==='explore')openModal('menu');}else if(e.code==='KeyM'&&mode==='explore')openModal('menu');});
  window.addEventListener('keyup',e=>{if(directions[e.code])keys.delete(directions[e.code]);});window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput();});
  for(const button of document.querySelectorAll('[data-dir]')){button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);if(mode==='explore'){keys.add(button.dataset.dir);pendingMove=button.dataset.dir;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>keys.delete(button.dataset.dir));}
  function route(x,y){const m=D.maps[state.map],npc=m.npcs.find(n=>n.x===x&&n.y===y),targets=npc?[[x,y-1],[x-1,y],[x+1,y],[x,y+1]].filter(([x,y])=>!C.blocked(m,x,y)):[[x,y]];if(targets.some(t=>t[0]===state.x&&t[1]===state.y)){if(npc){faceNPC(npc);talk(npc);}return;}const queue=[[state.x,state.y,[]]],seen=new Set([state.x+','+state.y]);let result=null;while(queue.length&&seen.size<m.w*m.h){const [xx,yy,p]=queue.shift();for(const [dir,dx,dy] of [['up',0,-1],['down',0,1],['left',-1,0],['right',1,0]]){const nx=xx+dx,ny=yy+dy,k=nx+','+ny;if(seen.has(k)||C.blocked(m,nx,ny))continue;seen.add(k);const np=p.concat(dir);if(targets.some(t=>t[0]===nx&&t[1]===ny)){result=np;break;}if(!m.portals.some(t=>t.x===nx&&t.y===ny))queue.push([nx,ny,np]);}if(result)break;}if(result){path=result;pathNPC=npc||null;}else toast('그곳까지 갈 수 없어요. 길이나 인물을 선택해 주세요.');}
  function faceNPC(n){state.dir=n.x>state.x?'right':n.x<state.x?'left':n.y>state.y?'down':'up';}
  canvas.addEventListener('click',e=>{if(mode!=='explore'||!state)return;const r=canvas.getBoundingClientRect(),x=Math.floor(((e.clientX-r.left)/r.width*320+cam.x)/16),y=Math.floor(((e.clientY-r.top)/r.height*200+cam.y)/16);route(x,y);});
  function frame(time){const s=state||demo;if(mode==='explore'&&state&&time-lastMove>125){const dir=pendingMove||[...keys].pop()||path.shift();pendingMove=null;if(dir){const oldMap=state.map,oldX=state.x,oldY=state.y;state=C.move(state,dir);lastMove=time;walkingUntil=time+130;if(state.x!==oldX||state.y!==oldY)tone(180);if(oldMap!==state.map){clearInput();autosave();hud();}if(!path.length&&pathNPC){const n=pathNPC;pathNPC=null;faceNPC(n);talk(n);}}const n=C.nearby(state);$('interactHint').hidden=!n;if(n)$('interactHint').textContent='Enter · '+n.name+'와 이야기하기';}
    const view=state||demo,m=D.maps[view.map];cam.x=m.w*16<320?(m.w*16-320)/2:Math.max(0,Math.min(m.w*16-320,view.x*16-152));cam.y=m.h*16<200?(m.h*16-200)/2:Math.max(0,Math.min(m.h*16-200,view.y*16-96));ctx.save();ctx.scale(3,3);A.world(ctx,{...view,walking:time<walkingUntil},cam,time);ctx.restore();requestAnimationFrame(frame);}
  // Read-only snapshot for automated playthroughs and debugging.
  window.Designmon={getState:()=>state?JSON.parse(JSON.stringify(state)):null,getMode:()=>mode};hud();requestAnimationFrame(frame);
})();
